## Question 1: Weekly Sales

In [ ]:
import numpy as np 
sales = np.array([1200, 1500, 1800, 1700, 1600, 2000, 2100])

# Find total sales.
Total_sales = np.sum(sales)
print(Total_sales)

# Find average sales.
average_sales = np.average(sales)
print(average_sales)

# Find highest sales.
highest_sales = np.max(sales)
print(highest_sales)

# Find lowest sales.
lowest_sales = np.min(sales)
print(lowest_sales)

# Find the day with maximum sales.
max_day_sales = np.argmax(sales) # argmax --> returns the index position of the Max value
print(max_day_sales)

# Find the day with minimum sales.
min_day_sales = np.argmin(sales) # argmin --> returns the index position of the Min value
print(min_day_sales)


11900
1700.0
2100
1200
6
0


# Question 2: Student Marks

In [16]:
import numpy as np
marks = np.array([67,45,89,90,78,56,99,100,34,81])

# Count students scoring above 80.
index = np.where(marks>80)
print(marks[index])

# Count failed students (<40).
index = np.where(marks<40)
print(marks[index])

# Find average marks.
average_marks = np.average(marks)
print(average_marks)

# Find top 3 marks.
slice = marks[0:3]
sort = np.sort(slice)
print(sort) 

# Sort the marks.
result = np.sort(marks)
print(result)

[ 89  90  99 100  81]
[34]
73.9
[45 67 89]
[ 34  45  56  67  78  81  89  90  99 100]


# Question 3: E-commerce Data

In [20]:
import numpy as np
prices = np.array([599,899,1299,399,499,999,799])

# Add 18% GST to every product.
gst_price = prices * 1.18
print(gst_price)

# Give a 20% discount.
discount = prices - (prices*0.20)
print(discount)


[ 706.82 1060.82 1532.82  470.82  588.82 1178.82  942.82]
[ 479.2  719.2 1039.2  319.2  399.2  799.2  639.2]


# Question 4: Product Ratings

In [21]:
import numpy as np
ratings = np.array([5,4,3,5,2,1,4,5,3,2,4,5])

# Count 5-star ratings.
count1 = np.where(ratings==5)
print(len(ratings[count1]))

# Count ratings below 3.
count2 = np.where(ratings == 3)
print(len(ratings[count2]))

# Percentage of satisfied customers (rating ≥4).
count3 = np.sum(ratings >= 4)
percentage = (count3 / len(ratings)) * 100
print("Percentage:", percentage)

4
2
Percentage: 58.333333333333336


# Question 5: weather Data
 

In [ ]:
import numpy as np 
temp = np.array([31,32,35,36,34,33,37,38,30,29])

# Average temperature.
avg_temp = np.average(temp)
print(avg_temp)

# Days above 35°C.
result = np.where(temp>35)
print(temp[result])

33.5
[36 37 38]


# Question 6: Image Processing

In [ ]:
import numpy as np 
image = np.array([
[120,130,140],
[150,160,170],
[180,190,200]
])

# Increase brightness by 30.
brightness_increase = image + 30
print(brightness_increase)

# Decrease brightness by 20%.
brightness_decrease = image - (20/100)
print(brightness_decrease)

# Find brightest pixel.
result = np.max(image)
print(result)

[[150 160 170]
 [180 190 200]
 [210 220 230]]
[[119.8 129.8 139.8]
 [149.8 159.8 169.8]
 [179.8 189.8 199.8]]
200


# Question 7: Stock Market 

In [ ]:
import numpy as np 
stock = np.array([210,215,220,208,230,240,238,250])

# Daily profit/loss.
daily_changes = np.diff(stock)
print(daily_changes)

# Highest jump.
Highest_jump = np.max(daily_changes)
print(Highest_jump)

# Lowest jump 
Lowest_jump = np.min(daily_changes)
print(Lowest_jump)

# Percentage Increase from Day 1
Percentage_increase = ((stock[-1] - stock[0]) / stock[0]) * 100
print(Percentage_increase)

[  5   5 -12  22  10  -2  12]
22
-12
19.047619047619047


# Question 8: Real Data Science Practice

In [ ]:
import numpy as np 
customers = np.array([
[101,24,4500],
[102,31,8000],              
[103,20,2500],      # Customer ID   }
[104,42,12000],     # Age           }---> Column names
[105,36,6000],      # Amount Spent  }
[106,28,15000]
])

# Average customer age.
average_age = np.mean(customers[:,1])
print("Average Customer Age:", average_age)

# Average purchase amount.
average_purchase = np.mean(customers[:,2])
print("Average Purchase Amount:", average_purchase)

# Customer spending the most
index = np.argmax(customers[:,2])
print("Customer ID:", customers[index,0])
print("Age:", customers[index,1])
print("Amount Spent:", customers[index,2])

# Customers spending above ₹7000.
index = np.where(customers[:,2] > 7000)
print(customers[index])

# Customers Younger Than 30.
result = customers[customers[:,1] < 30]
for customer in result:                     # ---> In loops customer take single rows at a time  
    print("Customer ID:", customer[0])
    print("Age:", customer[1])
    print("Amount:", customer[2])
    print()

# Oldest Customer 
index = np.argmax(customers[:,1])
print("Customer ID:", customers[index,0])
print("Age:", customers[index,1])
print("Amount:", customers[index,2])

# Youngest Customer
index = np.argmin(customers[:,1])
print("Customer ID:", customers[index,0])
print("Age:", customers[index,1])
print("Amount:", customers[index,2])

Average Customer Age: 30.166666666666668
Average Purchase Amount: 8000.0
Customer ID: 106
Age: 28
Amount Spent: 15000
[[  102    31  8000]
 [  104    42 12000]
 [  106    28 15000]]
Customer ID: 101
Age: 24
Amount: 4500

Customer ID: 103
Age: 20
Amount: 2500

Customer ID: 106
Age: 28
Amount: 15000

Customer ID: 104
Age: 42
Amount: 12000
Customer ID: 103
Age: 20
Amount: 2500
